# Длина строки.
line-length = 99
# Список директорий, которые не проверяются.
exclude = ["alembic"]

[lint]
# Список кодов правил или префиксов, которые необходимо включить в проверку.
select = ["E", "F", "I"]

[format]
# Использовать одинарные кавычки.
quote-style = "single"


[lint.isort]
# Объединяет все импорты из одного места в одну строку.
combine-as-imports = true